{
  "hash": "1d37a1fa4c523c1f7f38e094fbc20d04",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Confidence Intervals\"\nformat:\n  revealjs:\n    scrollable: true\n    theme: [default, styles.scss]\n    navigation-mode: vertical\n    controls-layout: bottom-right\n    controls-tutorial: true\n    incremental: false\n    code-fold: true\n    chalkboard:\n      src: notes/chalkboard_1a.json\n      storage: chalkboard_pres\n      theme: whiteboard\n      chalk-width: 4\nknitr:\n  opts_chunk: \n    echo: false\n    eval: true\n    message: false\n    warnings: false\n    comment: \"#>\" \n    error: true\n    \nrevealjs-plugins:\n  - pointer\n  - verticator\n\nfilters: \n  - reveal-header\n  - reveal-auto-agenda\n  - webr\n  \nauto-agenda:\n  bullets: numbered\n  heading: Learning Outcomes\n  \neditor: visual\n---\n\n\n\n\n# Confidence Intervals\n\n## Motivating Example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15b_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n## Motivating Example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15b_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## Linear Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- penguins %>% lm(body_mass_kg ~ species, data = .)\nres\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = body_mass_kg ~ species, data = .)\n#> \n#> Coefficients:\n#>      (Intercept)  speciesChinstrap     speciesGentoo  \n#>          3.70616           0.02692           1.38627\n```\n\n\n:::\n:::\n\n\n## Computing the mean\n\n$$\n\\hat Y = 3.71 + 0.03 \\times Chinstrap + 1.39 \\times Gentoo \n$$\n\n-   Adelie\n\n-   Chinstrap\n\n-   Gentoo\n\n## Confidence Interval\n\nThese are a collection of $\\beta_1$ values that will fail to reject the Null Hypothesis.\n\n::: fragment\nThe $\\beta_1$ values that are not different from our current estimate $b_1$\n:::\n\n## Confidence Interval\n\nThese are a collection of specific parameters that will fail to reject the null hypothesis.\n\n-   Adelie: $\\mu_a$\n\n-   Chinstrap: $\\mu_c$\n\n-   Gentoo: $\\mu_g$\n\n## Looking at Adelie\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15b_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n## Boostrap CI\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_mean <- function(x){\nmeans <- favstats(body_mass_kg ~ species, data = penguins) %>% \n  select(species, mean) %>%\n  t() %>% .[2,] |> as.numeric() \nreturn(tibble(adelie = means[1], \n                chinstrap = means[2], \n                gentoo = means[3]))\n}\nboot_means <- do(1000) * extract_mean(resample(penguins))\nprint(\"Adelie\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"Adelie\"\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(boot_means$adelie, probs = c(.025, .975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     2.5%    97.5% \n#> 3.706164 3.706164\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Chinstrap\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"Chinstrap\"\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(boot_means$chinstrap, probs = c(.025, .975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     2.5%    97.5% \n#> 3.733088 3.733088\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Gentoo\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"Gentoo\"\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(boot_means$gentoo, probs = c(.025, .975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     2.5%    97.5% \n#> 5.092437 5.092437\n```\n\n\n:::\n:::\n\n\n## Mathematical Models\n\nUse the `pairwise()` to compute confidence intervals.\n\nA difference occurs when 0 is not within the intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres %>% pairwise()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \n#>   group_1   group_2    diff pooled_se      q    df  lower upper p_adj\n#>   <chr>     <chr>     <dbl>     <dbl>  <dbl> <int>  <dbl> <dbl> <dbl>\n#> 1 Chinstrap Adelie    0.027     0.048  0.563   330 -0.132 0.186 .9164\n#> 2 Gentoo    Adelie    1.386     0.040 34.450   330  1.252 1.520 .0000\n#> 3 Gentoo    Chinstrap 1.359     0.050 27.444   330  1.194 1.524 .0000\n```\n\n\n:::\n:::\n\n\n## Plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres %>% pairwise(plot = T)\n```\n\n::: {.cell-output-display}\n![](15b_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \n#>   group_1   group_2    diff pooled_se      q    df  lower upper p_adj\n#>   <chr>     <chr>     <dbl>     <dbl>  <dbl> <int>  <dbl> <dbl> <dbl>\n#> 1 Chinstrap Adelie    0.027     0.048  0.563   330 -0.132 0.186 .9164\n#> 2 Gentoo    Adelie    1.386     0.040 34.450   330  1.252 1.520 .0000\n#> 3 Gentoo    Chinstrap 1.359     0.050 27.444   330  1.194 1.524 .0000\n```\n\n\n:::\n:::\n\n\n# Semester\n\n## Final\n\n-   Max of 30 Questions\n\n-   Mixed of Multiple Choice, True or False, and Free Response\n\n-   Get 1 sheet of notes, front and back\n\n-   In-person\n\n-   You are not allowed to talk to anyone during the exam\n\n-   You can use an inexpensive calculator, bring one\n\n-   All other electronic devices must be silenced an put away\n\n-   The exam is worth 100 points\n\n-   Write any explanations in the context of the problem\n\n## Final Material\n\n-   Linear Models\n\n-   Inference\n\n-   Confidence Intervals\n\n## MW 10 AM Class Final\n\nWednesday December 6\n\n8 AM - 10 AM\n\n## MW 2 PM Class Final\n\nWednesday December 6\n\n1 PM - 3 PM\n\n## When are Labs DUE\n\nDEC 7th 11:59 PM\n\n## When are Readings DUE\n\nDEC 7th 11:59 PM\n\n## When are Extra Credits DUE\n\nDEC 7th 11:59 PM\n\n# Course Evaluations\n\n## Please Complete Course Evaluations\n\n-   Complete them for all your courses\n\n# Complete Survey\n\n## Complete Survey\n\n![](img/frame%20(7).png){fig-align=\"center\"}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}